### ISSUE TITLE
TVMaze Plugin - 8.0.0.0 - Status is "Malfunctioned"

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin-plugin-tvmaze#31]
The TVMaze 8.0.0.0 no longer retrieves metadata.  When checking the plugins in the server dashboard, the status for the plugin is "Malfunctioned".

 - OS: Windows
 - Jellyfin Version: 10.7.6, stable

**To Reproduce**
1. Start the server
2. Open server in browser
3. Go to the Plugin section in the Dashboard
4. See that the status of the plugin

**Expected behavior**
The TVMaze plugin should startup correctly.

**Comment by Cookie-Monster-Coder** [comment]
v8 still install on 10.7.6

**Comment by crobibero** [comment]
I’m aware. Future plugin releases will have this issue fixed.

**Comment by Cookie-Monster-Coder** [comment]
Anyway to install V7 without it auto updating and causing it to be malfunctioned?
