### ISSUE TITLE
Proper name/case of the service is TVmaze

### ISSUE THREAD

**Issue by BMitrovic17** [jellyfin/jellyfin-plugin-tvmaze#8]
This is cosmetics only but regardless it should be fixed, we see different cases and different names overall.
`TvMaze`, `TV Maze`, `TVMaze` ... all are wrong, it's `TVmaze`

**Comment by crobibero** [comment]
I've updated all user-facing strings, hope that is good enough

**Comment by chenichadowitz** [comment]
This may or may not be related, but on my side I'm seeing two versions of the TVmaze plugin in my catalog. Checking the guid for both they appear identical:
![image](https://user-images.githubusercontent.com/3758336/114905909-7c19bd80-9de7-11eb-8acb-31d7c31b23f5.png)

https://my.jellyfin.domain/web/index.html#!/addplugin.html?name=TV%20Maze&guid=A4A488D0-17A3-4919-8D82-7F3DE4F6B209
vs
https://my.jellyfin.domain/web/index.html#!/addplugin.html?name=TVmaze&guid=A4A488D0-17A3-4919-8D82-7F3DE4F6B209

**Comment by crobibero** [comment]
I didn't realize the plugins are grouped by name, I will poke someone with access to fix it. Thanks for letting us know!
